### ISSUE TITLE
Support ARM64

### ISSUE THREAD

**Issue by justindthomas** [mietek/halcyon#100]
I'm using Ubuntu 14.04 and 16.04 on a Pine A64+ board. Ubuntu seems to work well on the device and `haskell-platform` is available in the standard Ubuntu repositories for the `aarch64` platform.

Unfortunately, Halcyon doesn't seem to recognize it. I tried altering `platform.sh` in bashmenot to call out the `linux-ubuntu-14.04-aarch64` platform, but more is obviously needed.

Is this something that could be added relatively easily? I really like Halcyon and would prefer not to monkey around with `haskell-platform` from the Ubuntu repos directly.

**Comment by mietek** [comment]
I’m sorry. This project is no longer maintained.
