### ISSUE TITLE
"sh setup.sh" encounter error

### ISSUE THREAD

**Issue by luckypoem** [mietek/halcyon#103]
hi.

root@AR:~# mkdir halcyon
root@AR:~# cd halcyon
root@AR:~/halcyon# wget https://github.com/mietek/halcyon/raw/master/setup.sh
root@AR:~/halcyon# sh setup.sh
setup.sh: 1: set: Illegal option -o pipefail
root@AR:~/halcyon#

how to fix it?

**Comment by mietek** [comment]
I’m sorry. This project is no longer maintained.
