### ISSUE TITLE
Create a tag?

### ISSUE THREAD

**Issue by jspahrsummers** [mietek/halcyon#15]
I'd love to submit Halcyon to [Homebrew](http://brew.sh) (though it remains to be seen whether they'll accept it), but one of their stipulations is that the project have tagged releases.

Could you please create a tag? :pray:

**Comment by mietek** [comment]
I’m reluctant to do this for a number of reasons:

- Currently, Halcyon doesn’t support installing native OS packages on OS X yet.  In fact, it would need to wrap around `brew` in a similar fashion to what is currently done for `apt-get` and `yum`.  I haven’t done that yet, and I don’t know if Homebrew allows OS packages to be installed in a separate directory.

- Halcyon updates itself automatically, to match the current _git_ `master`.  It’s likely this approach isn’t compatible with Homebrew package versioning.

- Installing Halcyon on OS X is just a matter of cloning the source code repository, and running `sudo mkdir /app && sudo chown $(id -u):$(id -g) app`, which you would have to do manually with Homebrew anyway.

**Comment by jspahrsummers** [comment]
> Currently, Halcyon doesn’t support installing native OS packages on OS X.

My goal wouldn't be use to Homebrew _through_ Halcyon, but rather to easily install Halcyon in a “standard” OS X way.

> Halcyon updates itself automatically, to match the current git master. It’s likely this approach isn’t compatible with Homebrew package versioning.

That's true, but the environment variable could be disabled.

> Since brew is meant to be used without sudo, you’d have to do this manually anyway.

My intention was to change the Halcyon root to point into the Homebrew directory, which is something that most OS X developers (at least, those who use Homebrew) would want.

Anyways, I'm happy to maintain it and do the work to conform to Homebrew conventions. I was just looking for a tag on the repo. :wink:

**Comment by mietek** [comment]
> My goal wouldn't be use to Homebrew through Halcyon, but rather to easily install Halcyon in a “standard” OS X way.

I get it.  It’s just that Halcyon isn’t fully functional on OS X yet, and so I don’t really want to present it as a solution for OS X users right now.

> Anyways, I'm happy to maintain it and do the work to conform to Homebrew conventions. I was just looking for a tag on the repo. 

Fair enough.  I’ve now tagged [_bashmenot_ v1.0.0](https://github.com/mietek/bashmenot/tree/v1.0.0) and [Halcyon v1.0.0](https://github.com/mietek/halcyon/tree/v1.0.0).  The [_bashmenot_ reference](https://bashmenot.mietek.io/reference/#environment-variables) and the [Halcyon reference](https://halcyon.sh/reference/#self-update-options) should help you.

**Comment by jspahrsummers** [comment]
> It’s just that Halcyon isn’t fully functional on OS X yet, and so I don’t really want to present it as a solution for OS X users right now.

Ah, okay. Are there are specific issues that you know about? I might be able to submit pull requests for them, if I have some spare time.

**Comment by mietek** [comment]
As I’ve said above: Halcyon doesn’t support installing native OS packages on OS X, while it does on Debian-based and RedHat-based Linux distributions. The issue is now tracked as https://github.com/mietek/bashmenot/issues/2.

**Comment by jspahrsummers** [comment]
Got it, thank you for the pointer.

**Comment by mietek** [comment]
Another issue with Homebrew:

By default, Halcyon restores binary packages from an S3 bucket defined by [`HALCYON_PUBLIC_STORAGE_URL`](https://halcyon.sh/reference/#halcyon_public_storage_url).  These packages are built with the default [`HALCYON_BASE`](https://halcyon.sh/reference/#halcyon_base), `/app`.  (Note: [`HALCYON_ROOT`](https://halcyon.sh/reference/#halcyon_root) has a different meaning!)

If you point HALCYON_BASE into the Homebrew directory, you’ll need to provide your own packages in your own S3 bucket, and point HALCYON_PUBLIC_STORAGE_URL to it.

**Comment by jspahrsummers** [comment]
If `HALCYON_ROOT` changes, but `HALCYON_PREFIX` does not, that will naturally affect `HALCYON_BASE`—but which key is the public storage dependent upon? Is it actually coupled to the full base path, or just the prefix?

**Comment by mietek** [comment]
No, that’s not correct.  Please re-read [`HALCYON_BASE`](https://halcyon.sh/reference/#halcyon_base), [`HALCYON_PREFIX`](https://halcyon.sh/reference/#halcyon_prefix), and [`HALCYON_ROOT`](https://halcyon.sh/reference/#halcyon_root).

ROOT does not affect BASE.  ROOT only affects PREFIX.  Both ROOT and PREFIX can be changed at will, on an app-by-app basis, because both only affect the `--prefix` option given to `cabal configure`.

BASE cannot be easily changed, as it affects paths hardcoded into GHC libraries, and most importantly, Cabal sandboxes.

**Comment by mietek** [comment]
Every archive created by Halcyon references `HALCYON_BASE`.  If the archived value doesn’t match the user-specified value, the archive is automatically rejected as corrupt and rebuilt.

**Comment by mietek** [comment]
Perhaps an example will help make things more clear.

By default, if you install the `hello` app by building from source, you will end up with the following directories:
```
/app/ghc/...
/app/cabal/...
/app/sandbox/...
/app/bin/hello
```

If you set `HALCYON_PREFIX` to, say, `/opt`, and install the app again, Halcyon will re-run `cabal configure` on the app, perform an incremental build on the app, and the result will be:
```
/app/ghc/...
/app/cabal/...
/app/sandbox/...
/app/bin/hello
/opt/bin/hello
```
(Halcyon never deletes installed apps.)

Now, let’s say you wipe both `/app` and `/opt`, set `HALCYON_BASE` to `/usr/local/Library/halcyon`, and install the app again.  Halcyon will install GHC from bindist, bootstrap _cabal-install_ from source, build a sandbox for the `hello` app from scratch, and perform an incremental build again, giving you:
```
/usr/local/Library/halcyon/ghc/...
/usr/local/Library/halcyon/cabal/...
/usr/local/Library/halcyon/sandbox/...
/opt/bin/hello
```

You wouldn’t normally use `HALCYON_ROOT`. It’s meant for more difficult scenarios, like Haskell on Heroku.

**Comment by jspahrsummers** [comment]
I see. Well, if `HALCYON_ROOT` shouldn't be changed, I'd rather not use a different public storage, so I guess the Homebrew package should wait for now. 

I'm happy to tackle https://github.com/mietek/bashmenot/issues/2 at some point, though.

**Comment by mietek** [comment]
Just to make it clear — I’m not trying to discourage you.  Changing `HALCYON_ROOT` will not help in this case.  It is meant for a difficult scenario, such as the one which occurs in Haskell on Heroku.

If you’re interested, take a look at [`buildpack.sh`](https://github.com/mietek/haskell-on-heroku/blob/master/src/buildpack.sh#L90).  On Heroku, we have to use `HALCYON_BASE=/app` and `HALCYON_PREFIX=/app`, and we _also_ have to deal with pre-existing Heroku files in the same directory.  To archive the install directory without pulling in those files, the app is temporarily installed in `${root_dir}/app`, which is then copied to `${build_dir}`, which finally will become `/app` at run-time.

Adding full OS X support is quite high on my TODO list, as I develop Halcyon on OS X.
