### ISSUE TITLE
It would be nice to be able to specify a folder/namespace in a bucket

### ISSUE THREAD

**Issue by ozataman** [mietek/halcyon#17]
... so it is possible to have users in an organization pool their private storage in a single bucket (instead of one per user)

**Comment by mietek** [comment]
What would be the benefit of doing that, as opposed to just creating additional buckets?

**Comment by ozataman** [comment]
I wouldn't want to create a bucket for each employee in the team; too much pollution at the root level.

**Comment by mietek** [comment]
Do you know you can already share a single bucket between multiple users, without requiring each user to share the same Amazon IAM credentials?  You just need to set up the appropriate IAM policies.

Additionally, with [`HALCYON_NO_CLEAN_PRIVATE_STORAGE`](https://halcyon.sh/reference/#halcyon_no_clean_private_storage), many users can work on a single app, without overwriting each other’s files.

I’m reluctant to introduce additional options, as there is already a significant number of them.  Let me know if the above sharing method isn’t enough for you.

**Comment by ozataman** [comment]
I certainly am aware of that and we use IAM *extensively* at work at Soostone. If halcyon is able to share the same repository among an arbitrary number of users while ensuring the items below, then it already has the feature I requested here:

- No potential for conflicts/overwrites/etc. among users
- No potential for one user seeing/downloading/modifying/etc. another user's private area. Not all users may have the same code permissions and it is a general good idea to achieve separation to avoid headaches.
- An easy way for a user to purge his/her private area, as that will eventually be required for *some* reason

I just could not see how these would be possible without being able to specify sub-folders within a bucket. With that, an org can use IAM rules to give each user a single subfolder, which is what I was suggesting in the first place:

s3://company-halycon-bucket/user1
s3://company-halycon-bucket/user2
...

**Comment by mietek** [comment]
Please try setting [`HALCYON_S3_BUCKET`](https://halcyon.sh/reference/#halcyon_s3_bucket) to your desired string (i.e. `company-halcyon-bucket/user1`) and let me know if it works the way you wish.

**Comment by mietek** [comment]
With https://github.com/mietek/bashmenot/commit/a7e57d30fea0eaa6fe37cbfcebcc142579f62206, specifying an S3 bucket together with a prefix is expected to work without errors:
```
$ export HALCYON_S3_BUCKET=example-bucket/example-prefix
```
