### ISSUE TITLE
Installing halcyon breaks pkg-config on my system

### ISSUE THREAD

**Issue by fsh** [mietek/halcyon#18]
I let Halcyon set up its paths in my .bash_profile, but it seems to set PKG_CONFIG_SYSROOT_DIR (why?) so now I get stuff like:

    $ pkg-config --cflags libpng12
    -I/app/sandbox/usr/include/libpng12  

which is wrong, since it was installed to /usr by my package manager. Is this really intentional? Did I misconfigure something?

Ubuntu 14.04, fresh install.

**Comment by mietek** [comment]
Thanks. This was an intentional but misguided attempt to support the automatic installation of native OS packages.  With https://github.com/mietek/halcyon/commit/8da0d8f2d35724ff4d20857d0eeae9d93477417b, `PKG_CONFIG_SYSROOT_DIR` is no longer set.
