### ISSUE TITLE
Missing dependencies when trying to install xmobar with configuration flag

### ISSUE THREAD

**Issue by fsh** [mietek/halcyon#19]
I'm trying to get halcyon to install xmobar:

At first I did

    halcyon install xmobar

which worked fine. But then I wanted to reinstall it with a configuration flag (with_xft). So I simply did

    halcyon install --extra-configure-flags="--flags=with_xft" xmobar

and hoped for the best. However, this fails with:

    Configuring xmobar-0.22.1...
       cabal: At least the following dependencies are missing:
       X11-xft >=0.2 && <0.4
    *** ERROR: Failed to configure app

I am a bit lost regarding all the options: I tried combining various options like `--extra-apps=X11-xft`, `--sandbox-extra-apps=X11-xft`, `--sandbox-extra-apps-constraints` and `--constraints` (the latter two I am unsure how to use, but I just put in `X11-xft-0.3.1`). I tried adding it to the `constraints` file under `.halcyon/xmobar-0.22.1`, and I finally tried deleting the latter directory entirely. Still the same failure.

**Comment by mietek** [comment]
The correct options to use in this case are [`HALCYON_EXTRA_OS_PACKAGES`](https://halcyon.sh/reference/#halcyon_extra_os_packages), for run-time use, and [`HALCYON_SANDBOX_EXTRA_OS_PACKAGES`](https://halcyon.sh/reference/#halcyon_sandbox_extra_os_packages), for build-time use.  Let me know if you can get it to work.

**Comment by mietek** [comment]
@fsh: Did you manage to get `X11-xft` installed with Halcyon?
