### ISSUE TITLE
Support Arch Linux fully

### ISSUE THREAD

**Issue by mietek** [mietek/halcyon#26]
The setup script already supports Arch Linux.  Everything is expected to work, except installing native OS packages declared with [`HALCYON_SANDBOX_EXTRA_OS_PACKAGES`](https://halcyon.sh/reference/#halcyon_sandbox_extra_os_packages) or [`HALCYON_EXTRA_OS_PACKAGES`](https://halcyon.sh/reference/#halcyon_extra_os_packages).

Be aware `pacman --sync --refresh` may [break things](http://pbrisbin.com/posts/dont_do_that/).

Depends on https://github.com/mietek/bashmenot/issues/3.

**Comment by edofic** [comment]
I have some issues installing GHC 7.10 (rc3) with Halcyon on Arch Linux. I can use 7.8.4 without problems as well as 7.10 (rc3) on ubuntu 14.

As far as I understand there is a problem building cabal from source as prepackaged cabal 1.22.0.0 is not available for arch. 

[Here is a log](https://gist.github.com/edofic/85773a771836d7db259f) of a failed `halcyon install`

**Comment by mietek** [comment]
@edofic: Indeed, a Cabal 1.22.0.0 directory archive for Arch Linux isn’t available in public storage right now.  This will be fixed soon.

The underlying problem is that _cabal-install_ cannot bootstrap with GHC 7.10.1-rc3 (https://github.com/haskell/cabal/issues/2461), and the fix isn’t included in any released version yet.

As a workaround, bootstrap Cabal 1.22.0.0 with GHC 7.8.4.

With private storage set up, Halcyon will automatically upload the resulting Cabal directory archive for later use, so you won’t have to bootstrap it again in the future, should you decide to switch to another Cabal version for a while.

**Comment by mietek** [comment]
Archives of Cabal 1.20.0.3, 1.22.0.0, and all supported GHC versions for Arch Linux are now available in public storage.

**Comment by mietek** [comment]
With https://github.com/mietek/halcyon/commit/8004eceaed1b2c98c54986b5b26936b9aa8875a4, `pacman --sync --refresh` is now gone from the setup script.

**Comment by mietek** [comment]
I’m sorry. This project is no longer maintained.
