### ISSUE TITLE
Tmp directory management ?

### ISSUE THREAD

**Issue by PierreR** [mietek/halcyon#27]
Can I safely delete halcyon files in the tmp directory ?

We have a rather strict polity on the allocated space of /tmp so I cannot let it grow too much.

Cheers

**Comment by mietek** [comment]
Everything which Halcyon creates in `/tmp` is temporary and can be safely removed.

Are you seeing any left-over files since https://github.com/mietek/halcyon/commit/db529454af779a0933e0bfdd50122707149164b7?  Halcyon should already be cleaning up after itself, even on failure.

**Comment by PierreR** [comment]
I can confirm that this problem has disappeared with the latest version.
Cheers.
