### ISSUE TITLE
Default to no-clean-private-storage

### ISSUE THREAD

**Issue by pbrisbin** [mietek/halcyon#28]
I have no idea, but I think it's more common to work on a multi-person team where it's desirable to have the `--no-clean-private-storage` behavior. I'd suggest making this the default. S3 is very cheap, and in general I would err on the side of keeping more data than reducing storage costs.

**Comment by mietek** [comment]
Thanks. This is related to improving local cache behaviour.

**Comment by danclien** [comment]
:+1: to making `--no-clean-private-storage` the default behavior. Storage is cheap. :)

**Comment by mietek** [comment]
I’m sorry. This project is no longer maintained.
