### ISSUE TITLE
Replace non-POSIX halcyon-paths command in documentation

### ISSUE THREAD

**Issue by pbrisbin** [mietek/halcyon#29]
Neither `source` nor `<( ... )` is POSIX. The most common approach in UNIX seems to be `eval`:

```
eval "$(halcyon paths)"
```

For two examples, see ssh-agent(1) and tset(1), find for "eval".

(OpenBSD links:
http://www.openbsd.org/cgi-bin/man.cgi/OpenBSD-current/man1/ssh-agent.1
http://www.openbsd.org/cgi-bin/man.cgi/OpenBSD-current/man1/tset.1
http://www.openbsd.org/cgi-bin/man.cgi/OpenBSD-current/man1/stat.1
)

**Comment by mietek** [comment]
The [`.` (dot) command](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_18) seems to be POSIX.

**Comment by pbrisbin** [comment]
Yes,

```
halcyon paths > foo && . ./foo
```

is another POSIX alternative. That said, the `eval` approach is simpler and there is much precedence in the UNIX world.

**Comment by mietek** [comment]
With https://github.com/mietek/halcyon/commit/b55f28465372ee0950e0cacb044cfe40f85f4dce and https://github.com/mietek/halcyon-website/commit/24875c3e37cafad1f59e694bd20c88030699a528, this is now done. Thanks for the suggestion.
