### ISSUE TITLE
setup.sh only works for Bash

### ISSUE THREAD

**Issue by pbrisbin** [mietek/halcyon#30]
I'd recommend either making it POSIX or clarifying in the documentation that you're expected to be in Bash when you run this.

**Comment by mietek** [comment]
Good point, thanks.

**Comment by mietek** [comment]
With https://github.com/mietek/halcyon/commit/4e4524fc058f761eb4a5c44d28f155addc4a69e6, this is slightly improved. More to come.

**Comment by mietek** [comment]
With 8ce8bb8fe1482341c00b55e4256a5f3d72fb837c, the setup script should now be entirely POSIX.
