### ISSUE TITLE
Support Amazon Linux

### ISSUE THREAD

**Issue by begriffs** [mietek/halcyon#31]
I'm trying to use Halcyon on the [Amazon Linux AMI](https://aws.amazon.com/amazon-linux-ami/) and I get this error:

```
-----> Welcome to Halcyon
-----> Creating base directory: /app
-----> Installing OS packages
*** ERROR: Unexpected platform: linux-amzn-2014.09-x86_64
*** ERROR: Failed to install OS packages
*** ERROR: Failed to install Halcyon
```

Wikipedia [says](https://en.wikipedia.org/wiki/Amazon_Machine_Image#Amazon_Linux_AMI) that this distro is basically rhel. Is there an environment variable or something I could set to get the installer to pick the right platform?

**Comment by mietek** [comment]
Not that simple.  I’ll do this after https://github.com/mietek/halcyon/issues/20.

**Comment by begriffs** [comment]
Thank you, and I'll try the manual steps in the meantime.

**Comment by begriffs** [comment]
I was able to install Halcyon manually on amazon linux but trying to use it to install a program runs into a related problem

```
*** ERROR: Unexpected platform: unknown
```

**Comment by mietek** [comment]
With https://github.com/mietek/halcyon/commit/76e99a395e1d22f9d3947127722ed9ce95cc39e6, Amazon Linux 2014.09 is now supported.

**Comment by begriffs** [comment]
You're a force of nature.
