### ISSUE TITLE
Halcyon is too pessimistic about changes in .halcyon

### ISSUE THREAD

**Issue by pbrisbin** [mietek/halcyon#32]
My understanding is that touching anything in .halcyon (or changing equivalent variables/passing equivalent flags?) will trigger a full sandbox and app rebuild. I think this is too pessimistic.

Specifically, any files/options which (only) affect the dependency graph should not trigger this, since Halcyon will resolve dependencies and find or build correct sandboxes based on the outcome anyway (right?).

There is one edge case I can think of: If I'm replacing a Hackage package with a modified fork (for example) via sandbox-sources, but I don't bump the version (even though I should), Halcyon would not consider this a change and wouldn't rebuild with the modified sources. However, I think it should be up to me to pass the appropriate rebuild flag or bump the version in the fork.

**Comment by mietek** [comment]
To be precise, changing any files matching `.halcyon/ghc*` or `.halcyon/sandbox*` (or changing equivalent variables/passing equivalent flags) will trigger a sandbox and app rebuild.

**Comment by pbrisbin** [comment]
Gotcha. I'd recommend allowing `sandbox-sources`, `sandbox-extra-apps`, and `sandbox-extra-apps-constraints/*` to change without triggering a rebuild.

We've discussed before that I also think it would make sense for `cabal*` to trigger the same level of cache-invalidation that `ghc*` does -- would you like that as a separate Issue?

**Comment by mietek** [comment]
Currently, the only magic files which could match `.halcyon/ghc*` or `.halcyon/cabal*` are hooks.  Changing GHC (or Cabal) hooks will change the GHC (or Cabal) magic hash, and effectively, change the GHC (or Cabal) version.

The impact of changing the GHC version is clear, as it’s encoded in S3 paths — everything needs to be built with the right GHC version.

See https://github.com/mietek/halcyon/issues/40 for more information about upcoming Cabal-related changes.

**Comment by mietek** [comment]
I’m sorry. This project is no longer maintained.
