### ISSUE TITLE
Wierd error when trying an install with puppet

### ISSUE THREAD

**Issue by PierreR** [mietek/halcyon#35]
I am trying to install `halcyon` using `puppet` and I have quite a wicket issue ... It is `puppet` related so I am just submit it here just in case you have an idea ...

I have tried this using a root user or an unprivilege one but it makes not difference.

Everything works fine without `puppet`. The same command works perfectly  if I use manually on a shell but when `puppet` try to install cabal I have got:

```
Debug: Exec[install-ghc](provider=posix): Executing '/bin/bash --login -c 'source <( /app/halcyon/halcyon paths ); halcyon install''
Debug: Executing '/bin/bash --login -c 'source <( /app/halcyon/halcyon paths ); halcyon install''
Notice: /Stage[main]/Profile::Jenkins::Slave::Halcyon/Exec[install-ghc]/returns: -----> Installing bashmenot... done, e2f1a00
Notice: /Stage[main]/Profile::Jenkins::Slave::Halcyon/Exec[install-ghc]/returns: -----> Installing GHC and Cabal
Notice: /Stage[main]/Profile::Jenkins::Slave::Halcyon/Exec[install-ghc]/returns:        External storage:                         public
Notice: /Stage[main]/Profile::Jenkins::Slave::Halcyon/Exec[install-ghc]/returns:        GHC version:                              7.8.4
Notice: /Stage[main]/Profile::Jenkins::Slave::Halcyon/Exec[install-ghc]/returns:        Cabal version:                            1.20.0.3
Notice: /Stage[main]/Profile::Jenkins::Slave::Halcyon/Exec[install-ghc]/returns:        Cabal repository:                         Hackage
Notice: /Stage[main]/Profile::Jenkins::Slave::Halcyon/Exec[install-ghc]/returns: 
Notice: /Stage[main]/Profile::Jenkins::Slave::Halcyon/Exec[install-ghc]/returns: -----> Restoring GHC directory
Notice: /Stage[main]/Profile::Jenkins::Slave::Halcyon/Exec[install-ghc]/returns:        Downloading https://halcyon.global.ssl.fastly.net/linux-centos-6-x86_64/halcyon-ghc-7.8.4.tar.gz... done
Notice: /Stage[main]/Profile::Jenkins::Slave::Halcyon/Exec[install-ghc]/returns:        Extracting halcyon-ghc-7.8.4.tar.gz... done, 699MB
Notice: /Stage[main]/Profile::Jenkins::Slave::Halcyon/Exec[install-ghc]/returns: 
Notice: /Stage[main]/Profile::Jenkins::Slave::Halcyon/Exec[install-ghc]/returns: -----> Locating Cabal directories
Notice: /Stage[main]/Profile::Jenkins::Slave::Halcyon/Exec[install-ghc]/returns:        Listing https://halcyon.global.ssl.fastly.net/?prefix=linux-centos-6-x86_64/halcyon-cabal-1.20.0.3-hackage-... done
Notice: /Stage[main]/Profile::Jenkins::Slave::Halcyon/Exec[install-ghc]/returns: -----> Restoring base Cabal directory
Notice: /Stage[main]/Profile::Jenkins::Slave::Halcyon/Exec[install-ghc]/returns:        Downloading https://halcyon.global.ssl.fastly.net/linux-centos-6-x86_64/halcyon-cabal-1.20.0.3.tar.gz... done
Notice: /Stage[main]/Profile::Jenkins::Slave::Halcyon/Exec[install-ghc]/returns:        Extracting halcyon-cabal-1.20.0.3.tar.gz... done, 13MB
Notice: /Stage[main]/Profile::Jenkins::Slave::Halcyon/Exec[install-ghc]/returns: -----> Updating Cabal directory
Notice: /Stage[main]/Profile::Jenkins::Slave::Halcyon/Exec[install-ghc]/returns:        Updating Cabal package database... error

```
This is strange because I do force a bash shell (login or not it makes no difference) by asking `puppet` to do the following:
```
  exec { 'install-ghc':
    user    => $jenkins_user,
    command => "/bin/bash --login -c 'source <( /app/halcyon/halcyon paths ); halcyon install'",
    creates => "${halcyon_base}/ghc",
    logoutput => on_failure,
    require => Exec['clone-halcyon']
  } 

```

Any idea ?

**Comment by mietek** [comment]
With https://github.com/mietek/halcyon/commit/985df904d51d5d2d6fd0a94087b3bd267f49d7ac, `cabal update` will now show more information on error.  Please try again and let me know what happens.

My suspicion is that Puppet restricts the amount of memory available to _cabal-install_, which triggers https://github.com/haskell/cabal/issues/2396.

Note that `halcyon install` will create `${`[`HALCYON_BASE`](https://halcyon.sh/reference/#halcyon_base)`}/ghc`, `${`[`HALCYON_BASE`](https://halcyon.sh/reference/#halcyon_base)`}/cabal`, and `${`[`HALCYON_CACHE`](https://halcyon.sh/reference/#halcyon_cache)`}`.

**Comment by PierreR** [comment]
I will try again on Monday.
 
Thanks so much for the tips !

**Comment by PierreR** [comment]
Here is the error I have after retrying:
```
Notice: /Stage[main]/Profile::Jenkins::Slave::Halcyon/Exec[install-ghc]/returns:        Updating Cabal package database... error
Notice: /Stage[main]/Profile::Jenkins::Slave::Halcyon/Exec[install-ghc]/returns:           *** ERROR: cabal_do: Expected existing .
Error: /app/halcyon/halcyon install returned 1 instead of one of [0]
```
It does not say anything about memory but there is one more line ...

**Comment by mietek** [comment]
Well, this is rather unexpected.  Can you try specifying a [`cwd`](https://docs.puppetlabs.com/references/latest/type.html#exec-attribute-cwd) for Puppet?  Make sure it exists.

**Comment by PierreR** [comment]
I have added `cwd`. I have now this error:
```
Notice: /Stage[main]/Profile::Jenkins::Slave::Halcyon/Exec[install-ghc]/returns: -----> Updating Cabal directory
Notice: /Stage[main]/Profile::Jenkins::Slave::Halcyon/Exec[install-ghc]/returns:        Updating Cabal package database... error
Notice: /Stage[main]/Profile::Jenkins::Slave::Halcyon/Exec[install-ghc]/returns:        cabal: HOME: does not exist
Error: /app/halcyon/halcyon install returned 1 instead of one of [0]
```

**Comment by mietek** [comment]
Cabal wants the user home directory to exist.  Please read the Puppet documentation for [`user`](https://docs.puppetlabs.com/references/latest/type.html#exec-attribute-user), [`home`](https://docs.puppetlabs.com/references/latest/type.html#user-attribute-home), [`managehome`](https://docs.puppetlabs.com/references/latest/type.html#user-attribute-managehome), and [`environment`](https://docs.puppetlabs.com/references/latest/type.html#cron-attribute-environment).

**Comment by PierreR** [comment]
Sorry I don't quite understand what you mean. The user `jenkins` has a `home` directory of course otherwise I guess `halcyon install` would not work when running on the shell. It is only when running with the `exec` puppet resource type that it fails.

**Comment by mietek** [comment]
Why desperate? The Puppet documentation for the [`user`](https://docs.puppetlabs.com/references/latest/type.html#exec-attribute-user) attribute of `exec` explicitly says:
> Please note that the $HOME environment variable is not automatically set when using this attribute.

**Comment by mietek** [comment]
Seems like the right fix, as the Puppet documentation for the [`user`](https://docs.puppetlabs.com/references/latest/type.html#exec-attribute-user) attribute of `exec` explicitly says:
> Please note that the $HOME environment variable is not automatically set when using this attribute.

**Comment by PierreR** [comment]
It does ! I really thought that using `/bin/bash -c` would set this up.

Thank you so much for your time, support and patience !
