### ISSUE TITLE
Pass flags to cabal freeze to ensure all targets are included

### ISSUE THREAD

**Issue by pbrisbin** [mietek/halcyon#36]
When trying to find a cached sandbox, Halcyon uses `cabal freeze` to determine the current dependency tree. By default, this excludes the test target (and maybe others?). The result is that if you add a test dependency, Halcyon may use an existing sandbox and not install the required packages. Trying to then run tests in this environment will fail.

The solution would be to pass `--enable-tests` to `cabal freeze`.

**Comment by mietek** [comment]
Note `cabal freeze` does not accept the same flags as `cabal configure` or `cabal install` — in particular, it ignores any `--constraint` flags (https://github.com/haskell/cabal/issues/2265).  With _cabal-install_ 1.22.0.0, `--enable-tests` is now accepted (https://github.com/haskell/cabal/issues/1827).

Perhaps the solution is to filter the acceptable flags (currently, the one acceptable flag) from [`HALCYON_SANDBOX_EXTRA_CONFIGURE_FLAGS`](https://halcyon.sh/reference/#halcyon_sandbox_extra_configure_flags), and hope for `cabal freeze` to reach flag parity with `cabal configure`?

**Comment by pbrisbin** [comment]
As a very quick fix, would you consider always passing `--enable-tests` to the `cabal freeze` invocation? This shouldn't hurt any applications that don't have a test target, and would fix those (like mine) that do.

**Comment by mietek** [comment]
With https://github.com/mietek/halcyon/commit/4758160bec35bc4af958ca2b81b15cde3f75a52f, any flags declared as [`HALCYON_SANDBOX_EXTRA_CONFIGURE_FLAGS`](https://halcyon.sh/reference/#halcyon_sandbox_extra_configure_flags) will be passed to `cabal freeze`, as long as they’re supported by the current _cabal-install_ version.
