### ISSUE TITLE
Improve Stackage support

### ISSUE THREAD

**Issue by mietek** [mietek/halcyon#41]
Using a particular Stackage snapshot appears to be a good alternative to explicitly specifying version constraints.

This is related to https://github.com/mietek/halcyon/issues/40.

**Comment by angerman** [comment]
Stockage might miss some packages though. E.g.

- `regex-compat-tdfa`
- `gitlib-libgit2`
- `RSA`

Thus, building with hackage might work, while building with stackage might not. (Though new packages are constantly added). This is where a stockage `cabal.config` gives you best of both worlds right now.

**Comment by mietek** [comment]
With https://github.com/mietek/halcyon/commit/77253b8e2c59cd4d377c10a87777f90d5bf23bd4, when using Stackage as the [`HALCYON_CABAL_REMOTE_REPO`](https://halcyon.sh/reference/#halcyon_cabal_remote_repo), Halcyon should no longer emit warnings about version constraints not being declared, and should no longer re-run `cabal update` daily.

**Comment by mietek** [comment]
It should be possible to ask Halcyon to pull in a particular Stackage `cabal.config`, even if it wasn’t included in the source directory — just as it is possible to specify [`HALCYON_CONSTRAINTS`](https://halcyon.sh/reference/#constraints) on the command-line.

Using a Stackage `cabal.config` would require changing the assumption that a constraints file (either `.halcyon/constraints` or `cabal.config`) for a particular app should list the complete set of packages which are the app’s direct or indirect dependencies, as generated by `cabal freeze`.

Switching from `cabal freeze` to `cabal install --dry-run` is likely to help (https://github.com/mietek/halcyon/issues/52).

**Comment by mietek** [comment]
It’s worth noting that the notion of a constraints file, named `cabal.freeze`, was mentioned in the original `cabal freeze` proposal, which was explicitly inspired by the features of `Gemfile.lock` (https://github.com/haskell/cabal/issues/1502).

Unfortunately, `cabal.freeze` didn’t make it into _cabal-install_, due to lack of time (https://github.com/haskell/cabal/pull/1519).

**Comment by gregwebs** [comment]
It wan't due to a lack of time, it was due to Johan mandating his design decision on the matter.

**Comment by mietek** [comment]
I’m sorry. This project is no longer maintained.
