### ISSUE TITLE
Support Windows

### ISSUE THREAD

**Issue by mietek** [mietek/halcyon#42]
Halcyon depends on [_bashmenot_](https://bashmenot.mietek.io/), which depends primarily on GNU _bash_.  Both projects already support Linux and BSD, so maybe supporting Windows with a Cygwin-like compatibility layer ([Gow](https://github.com/bmatzelle/gow), perhaps?) isn’t too far-fetched.

This depends on https://github.com/mietek/bashmenot/issues/7.

**Comment by 23Skidoo** [comment]
Is there some technical reason not to use MSYS? It also comes with Bash.

**Comment by mietek** [comment]
@23Skidoo:  Probably not; thanks for pointing it out.

MSYS looks to be the right choice, since it’s already used by [MinGHC](https://github.com/fpco/minghc).

**Comment by BethAr** [comment]
I assume MSYS is not enough to run on Windows? If not, is there any plans on increasing support?

**Comment by mietek** [comment]
@BethAr: MSYS still looks to be the right choice. I’d like to support Windows, eventually. However, I don’t use Windows, and there’s been little interest in Windows support so far.

**Comment by mietek** [comment]
I’m sorry. This project is no longer maintained.
