### ISSUE TITLE
Speed up stripping GHC on OS X

### ISSUE THREAD

**Issue by mietek** [mietek/halcyon#43]
Stripping most versions of GHC on OS X is, inexplicably, _much_ slower than stripping GHC 7.8.3 on OS X (all with `strip -u -r`), or than stripping the same GHC versions on other platforms (all with `strip --strip-unneeded`).  This affects both OS X 10.9 and 10.10.  All results refer to [official bindists](https://downloads.haskell.org/~ghc/) or [soon-to-be official bindists](http://www.ozonehouse.com/mark/platform/).

### OS X 10.10

| GHC               | Installed size | Doc-less size | Stripped size | Stripping time
| :---------------- | -------------: | ------------: | ------------: | -------------:
| _**7.10.1-rc2**_  | 920 MB         | 787 MB        | 728 MB        | _**100 minutes**_
| _**7.8.4**_       | 809 MB         | 679 MB        | 635 MB        | _**65 minutes**_
| 7.8.3             | 729 MB         | 600 MB        | 559 MB        | 188 seconds
| _**7.8.2**_       | 817 MB         | 691 MB        | 644 MB        | _**69 minutes**_
| _**7.6.3**_       | 856 MB         | 732 MB        | 636 MB        | _**54 minutes**_
| _**7.6.1**_       | 855 MB         | 731 MB        | 635 MB        | _**52 minutes**_
| _**7.4.2**_       | 842 MB         | 723 MB        | 629 MB        | _**50 minutes**_
| _**7.2.2**_       | 693 MB         | 581 MB        | 527 MB        | _**51 minutes**_
| _**7.0.4**_       | 647 MB         | 536 MB        | 487 MB        | _**49 minutes**_

### Ubuntu 14.04

| GHC         | Installed size | Doc-less size | Stripped size | Stripping time
| :---------- | -------------: | ------------: | ------------: | -------------:
| 7.10.1-rc2  | 1.1 GB         | 899 MB        | 811 MB        | 112 seconds
| 7.8.4       | 928 MB         | 789 MB        | 701 MB        | 100 seconds
| 7.8.3       | 928 MB         | 789 MB        | 701 MB        | 97 seconds
| 7.8.2       | 936 MB         | 801 MB        | 708 MB        | 96 seconds
| 7.6.3       | 893 MB         | 768 MB        | 650 MB        | 84 seconds
| 7.6.1       | 892 MB         | 767 MB        | 649 MB        | 87 seconds
| 7.4.2       | 876 MB         | 755 MB        | 641 MB        | 83 seconds
| 7.2.2       | 842 MB         | 728 MB        | 644 MB        | 82 seconds
| 7.0.4       | 797 MB         | 687 MB        | 598 MB        | 80 seconds

CC @mzero @etrepum

**Comment by mietek** [comment]
Thanks to @cartazio for pointing out @mzero’s builds have object splitting enabled, and the official GHC 7.8.3 bindist does not.  This can be verified by comparing the output of `ghc --info` between versions:
```
- ,("Object splitting supported","NO")
+ ,("Object splitting supported","YES")
```

**Comment by mietek** [comment]
Thanks to @cartazio for pointing out all affected bindists have object splitting enabled, while the official GHC 7.8.3 bindist does not.  Checking this takes about a minute:
```
vs=( 7.10.1-rc2 7.8.4 7.8.3 7.8.2 7.6.3 7.6.1 7.4.2 7.2.2 7.0.4 )
c=1.22.0.0
for v in ${vs[@]}; do
    halcyon install --ghc-version=$v --cabal-version=$c 2>/dev/null
    echo -n "$v: "
    ghc --info | grep splitting
    c=1.20.0.3
done
vs=( 7.10.1-rc2 7.8.4 7.8.3 7.8.2 7.6.3 7.6.1 7.4.2 7.2.2 7.0.4 )
c=1.22.0.0
for v in ${vs[@]}; do
    halcyon install --ghc-version=$v --cabal-version=$c 2>/dev/null
    echo -n "$v: "
    ghc --info | grep splitting
    c=1.20.0.3
done
```

**Comment by mietek** [comment]
Thanks to @cartazio for pointing out all affected bindists have object splitting enabled, while the official GHC 7.8.3 bindist does not.  Checking this takes about a minute:
```
vs=( 7.10.1-rc2 7.8.4 7.8.3 7.8.2 7.6.3 7.6.1 7.4.2 7.2.2 7.0.4 )
c=1.22.0.0
for v in ${vs[@]}; do
    halcyon install --ghc-version=$v --cabal-version=$c 2>/dev/null
    echo -n "$v: "
    ghc --info | grep splitting
    c=1.20.0.3
done
7.10.1-rc2:  ,("Object splitting supported","YES")
7.8.4:  ,("Object splitting supported","YES")
7.8.3:  ,("Object splitting supported","NO")
7.8.2:  ,("Object splitting supported","YES")
7.6.3:  ,("Object splitting supported","YES")
7.6.1:  ,("Object splitting supported","YES")
7.4.2:  ,("Object splitting supported","YES")
7.2.2:  ,("Object splitting supported","YES")
7.0.4:  ,("Object splitting","YES")
```

**Comment by mietek** [comment]
Looks like object splitting is implicated in [other issues](https://ghc.haskell.org/trac/ghc/wiki/Building/Troubleshooting#Argumentlisttoolong):
> **Argument list too long**
> … That stops the splitting-up of object files, and dramatically reduces the number of object files involved. Link times are also improved. (Binary size increases though.)

**Comment by mzero** [comment]
If you don't have split obj enabled, then even the simplest "Hello World"
program is gigantic. Base simply has too much stuff in it to be a single .o!

The other issues related to having many small .o files generally aren't
seen on Mac OS X.

You seem to have the earlier 7.8.3 - I had built one that wasn't split obj,
but then released an updated version. The version in the platform is split
obj.

Quesion: Should we be shipping stripped versions instead? I'd be willing to
do the stripping before shipping.

- Mark

**Comment by mietek** [comment]
The GHC 7.8.3 I’ve tested comes straight from the official site, as you can see in [`src/ghc.sh`](https://github.com/mietek/halcyon/blob/master/src/ghc.sh#L83):
```bash
map_ghc_version_to_osx_x86_64_url () {
	local ghc_version
	expect_args ghc_version -- "$@"

	# TODO: Improve cross-version compatibility.
	case "${ghc_version}" in
	'7.10.1-rc2')	echo 'http://www.ozonehouse.com/mark/platform/ghc-7.10.0.20150123-x86_64-apple-darwin.tar.bz2';;
	'7.8.4')	echo 'http://www.ozonehouse.com/mark/platform/ghc-7.8.4-x86_64-apple-darwin.tar.bz2';;
	'7.8.3')	echo 'https://downloads.haskell.org/~ghc/7.8.3/ghc-7.8.3-x86_64-apple-darwin.tar.xz';; # 10.7+
	'7.8.2')	echo 'https://downloads.haskell.org/~ghc/7.8.2/ghc-7.8.2-x86_64-apple-darwin-mavericks.tar.xz';; # 10.9 only?
	'7.6.3')	echo 'https://downloads.haskell.org/~ghc/7.6.3/ghc-7.6.3-x86_64-apple-darwin.tar.bz2';; # 10.7+?
	'7.6.1')	echo 'https://downloads.haskell.org/~ghc/7.6.1/ghc-7.6.1-x86_64-apple-darwin.tar.bz2';; # 10.7+?
	'7.4.2')	echo 'https://downloads.haskell.org/~ghc/7.4.2/ghc-7.4.2-x86_64-apple-darwin.tar.bz2';; # 10.7+?
	'7.2.2')	echo 'https://downloads.haskell.org/~ghc/7.2.2/ghc-7.2.2-x86_64-apple-darwin.tar.bz2';; # 10.6+?
	'7.0.4')	echo 'https://downloads.haskell.org/~ghc/7.0.4/ghc-7.0.4-x86_64-apple-darwin.tar.bz2';; # 10.6+?
	*)
		log_error "Unexpected GHC version for OS X (x86_64): ${ghc_version}"
		return 1
	esac
}
```
I’d like to know which bindists support which OS X versions, as I’m not currently sure about that.  I think all GHC 7 versions should support at least 10.9 and 10.10.  I’m not sure how much demand is there for earlier versions.

With regard to stripping — each GHC installation made with Halcyon is already stripped, by running [`strip_tree`](https://github.com/mietek/bashmenot/blob/master/src/tar.sh#L258) over the entire GHC installation directory.  This has caused no issues since at least June 2014, so my opinion is — yes, we should be shipping stripped versions, with no documentation included.

**Comment by mietek** [comment]
To clarify — this issue is mostly a concern for myself, as GHC stripping usually happens once, when I prepare the archives to be made available in Halcyon public storage.  However, I’ve made it simple for the cautious user to disable public storage (by setting [`HALCYON_NO_PUBLIC_STORAGE=1`](https://halcyon.sh/reference/#public-storage-options)), and trust only bindists downloaded from the official site.  I’d like for this to remain a viable option, but a 2-hour stripping process makes it less-than-ideal.

**Comment by mietek** [comment]
With 3419002e25ffba8f3b7d951108479cda37dd9642, stripping the GHC directory can now be disabled with `HALCYON_GHC_NO_STRIP`.

With e1392651f0ae91dd31138abe50b28be12db9a96d, if stripping GHC is not disabled, on OS X, Halcyon now detects split objects and warns the user:
```
$ halcyon install --ghc-rebuild
-----> Installing GHC and Cabal
       External storage:                         private and public
       GHC version:                              7.8.4
       Cabal version:                            1.20.0.3
       Cabal remote-repo:                        hackage:http://hackage.haskell.org/packages/archive

-----> Building GHC directory
       Downloading https://halcyon.global.ssl.fastly.net/original/ghc-7.8.4-x86_64-apple-darwin.tar.xz... done
       Extracting ghc-7.8.4-x86_64-apple-darwin.tar.xz... done, 820MB
-----> Installing GHC
       ...
-----> GHC installed, 809MB
       Removing documentation from GHC directory... done, 679MB
   *** WARNING: Split objects detected
   *** WARNING: Expected time to strip GHC directory: 30-120 minutes
   *** WARNING: To disable stripping GHC directory, set HALCYON_GHC_NO_STRIP to 1
       Stripping GHC directory... ^C
```
