### ISSUE TITLE
Add curl as dependency

### ISSUE THREAD

**Issue by noteed** [mietek/halcyon#44]
I'm in the `linux-ubuntu-14` case (in `setup.sh`), which installs

- build-essential
- git
- pigz
- zlib1g-dev

I'm on a clean system and it would be nice to add explicitely `curl` in the above list. (Halcyon simply fails to download anything, but it was unclear at first that curl was missing.)

Thanks a lot for working on this!

**Comment by mietek** [comment]
Can you paste the output of the setup script failing to run?

**Comment by noteed** [comment]
```
root@919f3d1eb031:/# /app/halcyon/halcyon install --ghc-version 7.8.4
-----> Installing bashmenot... done, 54bb20c
-----> Installing GHC and Cabal
       External storage:                         public
       GHC version:                              7.8.4
       Cabal version:                            1.20.0.3
       Cabal repository:                         Hackage

-----> Restoring GHC directory
       Downloading https://halcyon.global.ssl.fastly.net/linux-ubuntu-14.04-x86_64/halcyon-ghc-7.8.4.tar.gz...  (unknown)
       Retrying in 2 seconds (1/5)...  (unknown)
       Retrying in 4 seconds (2/5)...  (unknown)
       Retrying in 8 seconds (3/5)...  (unknown)
       Retrying in 16 seconds (4/5)...  (unknown)
-----> Building GHC directory
       Downloading https://halcyon.global.ssl.fastly.net/original/ghc-7.8.4-x86_64-unknown-linux-deb7.tar.xz...  (unknown)
       Retrying in 2 seconds (1/5)...  (unknown)
       Retrying in 4 seconds (2/5)...  (unknown)
       Retrying in 8 seconds (3/5)...  (unknown)
       Retrying in 16 seconds (4/5)...  (unknown)
       Downloading https://downloads.haskell.org/~ghc/7.8.4/ghc-7.8.4-x86_64-unknown-linux-deb7.tar.xz...  (unknown)
       Retrying in 2 seconds (1/5)...  (unknown)
       Retrying in 4 seconds (2/5)...  (unknown)
       Retrying in 8 seconds (3/5)...  (unknown)
       Retrying in 16 seconds (4/5)...  (unknown)
root@919f3d1eb031:/#
```

**Comment by noteed** [comment]
If you want to easily reproduce the problem, here is the Dockerfile I'm using (simply remove `curl` from the the apt-get install line):

```
FROM ubuntu:14.04

RUN apt-get update
RUN apt-get install -q -y language-pack-en
RUN update-locale LANG=en_US.UTF-8

RUN apt-get install -q -y build-essential curl git pigz zlib1g-dev

RUN mkdir -p /app
# RUN chown halcyon /app

RUN git clone https://github.com/mietek/halcyon /app/halcyon
RUN /app/halcyon/halcyon install --ghc-version 7.8.4
```

**Comment by mietek** [comment]
Thanks.  The problem here is, the setup script uses `curl` in order to detect which platform it’s running on.  In my testing, Ubuntu 14 base images on DigitalOcean and Heroku include `curl`.

Does your base image have `wget` installed?

**Comment by noteed** [comment]
Oh indeed, I was mixing halcyon itself with the setup script. I didn't use the setup script; I looked at it to see the dependencies I needed then only run `halcyon install`.

Here there is no wget either (but I can add it just as I can add curl).

In some way I assumed that the ["Set up" instructions](https://halcyon.sh/tutorial/#set-up), when only cloning the halcyon GitHub repository, was to have a peek at `setup.sh` to see the OS dependencies. Mentioning that curl is necessary and check for its existence would be good enough (no need to go through great length to detect the platform in some other way).

**Comment by mietek** [comment]
Note to self: The Debian 7, FreeBSD 9.3, and FreeBSD 10.1 images available on Amazon EC2 do not include _curl_, either.

**Comment by mietek** [comment]
With 4b4710df4dc140a0e42e1afafa9cc90b3259877d, the setup script now refuses to run if _curl_ is not available.
