### ISSUE TITLE
Increase isolation

### ISSUE THREAD

**Issue by mietek** [mietek/halcyon#46]
Avoid making any changes to the user’s home directory.
- [ ] When running the setup script for the first time, Halcyon extends `~/.bash_profile` to source the script output by [`halcyon paths`](https://halcyon.sh/reference/#halcyon-paths).  This should be made optional.
- [x] When installing an app, Halcyon tries to create a symlink pointing `~/.cabal/config` to the config file located in `HALCYON_BASE/cabal`, and emits a warning if `~/.cabal/config` already exists.  This is intended to ensure the user is using the same Cabal config as Halcyon, and isn’t needed by Halcyon itself.  This should be replaced by setting the (undocumented?) `CABAL_CONFIG` environment variable in [`halcyon paths`](https://halcyon.sh/reference/#halcyon-paths).
- [x] Halcyon immediately fails with an error if `~/.ghc` exists, due to https://github.com/mietek/halcyon/issues/5 and the underlying https://github.com/haskell/cabal/issues/2400.  This should be turned into a warning.
- [x] [`HALCYON_NO_MODIFY_HOME`](https://halcyon.sh/reference/#halcyon_no_modify_home) should be removed as no longer necessary.

CC @snoyberg

**Comment by mietek** [comment]
I’m planning to replace [`halcyon paths`](https://halcyon.sh/reference/#halcyon-paths) with `halcyon activate`.

The `halcyon activate` command will be opt-in — that is, it won’t be automatically added to `~/.bash_profile` by the setup script, but instead, it’ll be meant to be used manually, as follows:
```
$ eval "$( halcyon activate )"
```

This will make it possible for `halcyon activate` to automatically point _cabal-install_ to the Halcyon sandbox, by setting `CABAL_SANDBOX_CONFIG` to `HALCYON_BASE/sandbox/cabal.sandbox.config`, allowing users to easily use `cabal` commands in the Halcyon environment (https://github.com/mietek/halcyon/issues/47, https://github.com/mietek/halcyon/issues/59).

**Comment by aloiscochard** [comment]
:+1:

**Comment by mietek** [comment]
I’m sorry. This project is no longer maintained.
