### ISSUE TITLE
Make using local sandboxes easier

### ISSUE THREAD

**Issue by passy** [mietek/halcyon#47]
(I had a brief look through the other open issues mentioning "sandbox", I hope I didn't miss a duplicate of this one.)

I only found out through the [Giant Robots](https://robots.thoughtbot.com/building-haskell-projects-with-halcyon) blog post that you can actually link the global sandbox config to your local project, e.g. through

```bash
ln -sf /app/sandbox/cabal.sandbox.config .
```

This means that my editor integration now works again as expected and I can use `cabal repl` like I'd normally do. Would it be possible to set this up automatically, maybe as part of `halcyon build` in a project directory? Or would this interfere with your vision of how halcyon should be used?

**Comment by mietek** [comment]
Thanks.  This is a good question.  Indeed, perhaps the sandbox config should be automatically linked, and certainly, the possibility of doing so should be clearly documented.

Halcyon grew out of the Haskell on Heroku project, which is why it’s focused on workflows enabled by the `halcyon install` command.  There is much which could be done to improve `halcyon build` workflows, especially when working without private storage.

This is related to #14, #23, and #28.

**Comment by mietek** [comment]
I forgot to mention that when installing with [`HALCYON_KEEP_DEPENDENCIES`](https://halcyon.sh/reference/#halcyon_keep_dependencies), a symlink to `HALCYON_BASE/sandbox/cabal.sandbox.config` is already automatically created in `HALCYON_PREFIX/cabal.sandbox.config`.  With the default values fo both options, this amounts to:
```
ln -fs /app/sandbox/cabal.sandbox.config /app/cabal.sandbox.config
```
This is probably only useful on Heroku, where the home directory, source directory, default working directory, base directory, and prefix directory are all `/app`.

**Comment by mietek** [comment]
It occurred to me it’s possible to set the (undocumented?) `CABAL_SANDBOX_CONFIG` environment variable to point to `HALCYON_BASE/sandbox/cabal.sandbox.config`.  This avoids the need to mess around with symlinks, and can be done automatically, as part of activating the Halcyon environment.

As part of https://github.com/mietek/halcyon/issues/46, I’ll deprecate `halcyon paths` and introduce `halcyon activate`, which will set `CABAL_SANDBOX_CONFIG`.

CC @pbrisbin

**Comment by mietek** [comment]
Improving the related documentation is now tracked as https://github.com/mietek/halcyon-website/issues/2.
