### ISSUE TITLE
Use `cabal install --enable-tests --dependencies-only --dry-run` instead of `cabal freeze`?

### ISSUE THREAD

**Issue by danclien** [mietek/halcyon#52]
Doing `cabal install --enable-tests --dependencies-only --dry-run` in a clean sandbox gives similar results to using `cabal freeze`. This would help resolve/avoid the following issues:
- #1 – Unexpected constraints difference
  - May be not relevant if not using `cabal freeze`
  - I'm assuming `cabal install --enable-tests --dry-run` would match `cabal sandbox hc-pkg list`. I haven't confirmed though.
- #36 – Pass flags to cabal freeze to ensure all targets are included
  - Skips using `cabal freeze` altogether and grabs the testing dependencies correctly
- #41 – Improve Stackage support
  - Avoids issues with `cabal freeze` [not respecting constraints](https://github.com/mietek/halcyon/blob/master/src/cabal.sh#L848)
  - Should work with Stackage with a `cabal.config` file located in the app directory
- https://github.com/haskell/cabal/issues/1908 – Self-constraint generated by 'freeze' 
  - Avoids requiring Cabal 1.22
    - [Cabal 1.22 with ghc-mod is broken without GHC 7.10](https://github.com/kazu-yamamoto/ghc-mod/issues/437)
    - [GHC 7.10 is not fully supported by Stackage yet](https://github.com/fpco/stackage/issues/378)
  - Added in response to @mietek's [comment](https://github.com/mietek/halcyon/issues/52#issuecomment-77464646) below

I grabbed the output of both on one of our internal projects, and the output can be seen [here](https://gist.github.com/danclien/15c195e47f7b56e6225f). Output from `cabal freeze` was altered using `sed` to make differences easier to notice.

Major differences:
- `cabal freeze` includes packages included with GHC. e.g. The ones listed in `/app/ghc/lib/ghc-7.8.4/package.conf.d`
- `cabal freeze` has a cleaner, more consistent output format
  -  `cabal install --enable-tests --dry-run` indicated when there a newer version
    - e.g. `blaze-builder-0.3.3.4 (latest: 0.4.0.1)`

**Comment by mietek** [comment]
Thank you. This is a model feature request. Much appreciated.

**Comment by mietek** [comment]
Getting rid of `cabal freeze` would also avoid https://github.com/haskell/cabal/issues/1908, which is still an issue for _cabal-install_ versions prior to 1.22.0.0.

**Comment by mietek** [comment]
Another benefit is, the GHC version would not be automatically over-constrained.  Currently, since `cabal freeze` includes a version constraint for the `base` package, the GHC version is constrained down to the second decimal point; e.g. `base-4.7.0.2` constrains GHC to 7.8.4.

As a consequence, it should be possible to declare [`HALCYON_GHC_VERSION`](https://halcyon.sh/reference/#halcyon_ghc_version) in a magic file.

**Comment by mietek** [comment]
Replacing `cabal freeze` would also allow using _cabal-install_ versions prior to 1.20.0.0.

**Comment by thorinii** [comment]
What's needed to do this? Are we waiting for an update to cabal, or is it parsing a different format, or...?

**Comment by mietek** [comment]
@thorinii: In a word, time — to design, and to implement.

**Comment by mietek** [comment]
Perhaps it’d be worth to consider supporting separate sets of version constraints for different GHC versions.  Perhaps even separate `.halcyon/$GHC_VERSION` directories.

**Comment by mietek** [comment]
I’m sorry. This project is no longer maintained.
