### ISSUE TITLE
Add option to not remove generated Haddock/documentation in sandbox

### ISSUE THREAD

**Issue by danclien** [mietek/halcyon#54]
We use the documentation generated in the sandbox.

**Comment by mietek** [comment]
Related options which could be added:

- [ ] Disable removing documentation from the GHC directory?
- [ ] Disable removing documentation from the sandbox directory
- [ ] Disable stripping the GHC directory?
- [ ] Disable stripping the Cabal directory?
- [ ] Disable stripping the sandbox directory?
- [ ] Disable stripping the app directory

**Comment by mietek** [comment]
With https://github.com/mietek/halcyon/commit/752280014a94f62c3a86f20107492343cc9516e1 and https://github.com/mietek/halcyon/commit/3419002e25ffba8f3b7d951108479cda37dd9642, the following options are now available:

- `HALCYON_GHC_NO_REMOVE_DOC`
- `HALCYON_SANDBOX_NO_REMOVE_DOC`
- `HALCYON_APP_NO_REMOVE_DOC`
- `HALCYON_GHC_NO_STRIP`
- `HALCYON_CABAL_NO_STRIP`
- `HALCYON_SANDBOX_NO_STRIP`
- `HALCYON_APP_NO_STRIP`

**Comment by mietek** [comment]
@danclien: Please let me know if `HALCYON_SANDBOX_NO_STRIP` offers an improvement to your workflow.

**Comment by mietek** [comment]
@danclien: Please let me know if `HALCYON_SANDBOX_NO_REMOVE_DOC` offers an improvement to your workflow.
