### ISSUE TITLE
Use --progress-bar in curl calls

### ISSUE THREAD

**Issue by pbrisbin** [mietek/halcyon#55]
Sometimes the S3 downloads take a bit, it'd be nice to have progress output.

**Comment by mietek** [comment]
I agree.  Unfortunately, processing _curl_ output breaks the progress bars.  Compare:
```
$ curl --progress-bar https://halcyon.global.ssl.fastly.net/osx-10.10-x86_64/halcyon-ghc-7.8.4.tar.gz 2>&1 >/dev/null
```
```
$ curl -L --progress-bar https://halcyon.global.ssl.fastly.net/osx-10.10-x86_64/halcyon-ghc-7.8.4.tar.gz 2>&1 >/dev/null | sed 's/^/      /'
```

**Comment by pbrisbin** [comment]
I was afraid of that and almost mentioned it in my description. I can't think of a good solution :/

**Comment by mietek** [comment]
This is now tracked as part of https://github.com/mietek/bashmenot/issues/10.
