### ISSUE TITLE
Downloading tutorial constraints?

### ISSUE THREAD

**Issue by feuerbach** [mietek/halcyon#57]
I was pretty surprised to see this while trying to build my project (which has nothing to do with these tutorials):

```
-----> Examining partially-matching sandbox directories
       Downloading https://halcyon.global.ssl.fastly.net/linux-ubuntu-12.04-i386/ghc-7.8.4/halcyon-sandbox-f458aa8-halcyon-tutorial-1.0.constraints... done
       Downloading https://halcyon.global.ssl.fastly.net/linux-ubuntu-12.04-i386/ghc-7.8.4/halcyon-sandbox-f458aa8-haskell-on-heroku-tutorial-1.0.constraints... done
```

**Comment by mietek** [comment]
We’ve now spoken on IRC, and I believe your questions have been answered.  However, perhaps this is still an issue with the documentation.

Have you read the [“Build the sandbox”](https://halcyon.sh/tutorial/#build-the-sandbox) step of the Halcyon tutorial before attempting to build your project?

**Comment by feuerbach** [comment]
This probably psychological. I'm not comfortable with basing my production system on something called tutorial or haskell-on-heroku, since those things have nothing to do with my project. Maybe if the names were more generic (haskell-platform, or stackage, or something along those lines), I wouldn't have an issue.

**Comment by mietek** [comment]
I’m sorry you’ve had an uncomfortable experience.

The files downloaded contain version constraints for packages included in the sandbox directory archives available in public storage, and are used as part of speeding up the sandbox build process.  If your project’s dependencies weren’t a superset of any of the available sets, subsequent messages should’ve informed you the files weren’t going to be used:
```
-----> Scoring partially-matching sandbox directories
       Ignoring halcyon-tutorial-1.0 (f458aa8) as ... is not needed
       Ignoring haskell-on-heroku-tutorial-1.0 (f458aa8) as ... is not needed
```

You can prevent Halcyon from looking at anything available in public storage by setting [`HALCYON_NO_PUBLIC_STORAGE`](https://halcyon.sh/reference/#halcyon_no_public_storage) to `1`, or using the `--no-public-storage` command-line option.

**Comment by mietek** [comment]
The scoring process could be performed server-side, but I’ve elected to keep it client-side for now, as moving to package-level granularity would sidestep the issue altogether.
