### ISSUE TITLE
Support for Google Cloud Storage

### ISSUE THREAD

**Issue by opensourcegeek** [mietek/halcyon#58]
Are there any plans to support Google Cloud Storage?

**Comment by mietek** [comment]
It looks like no special support is required.  Google says in [“Migrating from Amazon S3 to Google Cloud Storage”](https://cloud.google.com/storage/docs/migrating):
> - Change the request endpoint to use the [Google Cloud Storage request endpoint.](https://cloud.google.com/storage/docs/concepts-techniques#endpoints)
> - Replace the Amazon Web Services (AWS) access and secret key with the corresponding Google Cloud Storage access key and secret key (collectively called your Google developer key).

Have you tried this?

**Comment by mietek** [comment]
You’ll need to set [`HALCYON_S3_ENDPOINT`](https://halcyon.sh/reference/#halcyon_s3_endpoint) for the request endpoint, [`HALCYON_AWS_ACCESS_KEY_ID`](https://halcyon.sh/reference/#halcyon_aws_access_key_id) for the access key, and [`HALCYON_AWS_SECRET_ACCESS_KEY`](https://halcyon.sh/reference/#halcyon_aws_secret_access_key) for the secret key.

Finally, there’s [`HALCYON_S3_BUCKET`](https://halcyon.sh/reference/#halcyon_s3_bucket), which I assume you’ll also need to set.

**Comment by opensourcegeek** [comment]
I haven't tried it yet - will take a look tomorrow. Cheers!

**Comment by mietek** [comment]
@opensourcegeek: Any updates?

**Comment by mietek** [comment]
@opensourcegeek: ping

**Comment by mietek** [comment]
Closing as inactive. Please comment when needed.
