### ISSUE TITLE
Continuous compilation mode

### ISSUE THREAD

**Issue by thorinii** [mietek/halcyon#62]
It'd be great for development to have a mode where you'd execute: `halcyon ~build` (note the tilde), and it would do a build like normal. After that however, it would sit there and watch the source directory for changes.

Every time a file is changed, it copies (as usual) the source directory and runs a build. This could be accomplished with programs like inotifywatch - in which case it'd be an optional feature depending on whether the user has it installed. Even better than `~build` would be `~test` - which would run a build and the tests in the same fashion.

This might be more conducive to smaller, faster-building projects. But it'd be great to give it a go. Let me know if I can help with this.

This is reminiscent of [sbt's continuous compilation/testing](http://www.scala-sbt.org/0.12.4/docs/Getting-Started/Running.html#continuous-build-and-test) where sbt will watch the sources and compile and test repeatedly for you.

**Comment by mietek** [comment]
Have you considered using the excellent cross-platform [_fswatch_](https://github.com/emcrisostomo/fswatch) to run `halcyon build`?

**Comment by thorinii** [comment]
Hmm the syntax is a bit complicated... I'll have to write a bash alias/function to help me :-). Seems to work well.

**Comment by mietek** [comment]
Good. I’d rather not extend Halcyon with additional features until more important work is complete.
