### ISSUE TITLE
Improve the setup script

### ISSUE THREAD

**Issue by taladar** [mietek/halcyon#63]
The setup.sh script assumes (for no particular reason) that Gentoo has no sudo even though the package is installed on my system, perhaps it should actually check if sudo is in the path instead or ask the user if it is not sure if the user running setup.sh has sudo access.

It also handles the various install steps badly in this case, printing instructions what to do manually but without aborting the run. If one then performs the steps manually and runs it again it  aborts with an error because the /app directory already exists.

**Comment by mietek** [comment]
Thanks.  This is a fair point.

**Comment by mietek** [comment]
This will also be resolved soon, following https://github.com/mietek/halcyon/issues/46.

CC @pharpend

**Comment by mietek** [comment]
I’m sorry. This project is no longer maintained.
