### ISSUE TITLE
pipefail not recognized

### ISSUE THREAD

**Issue by dschalk** [mietek/halcyon#66]
My default shell is zsh. The setup script aborted with a message saying pipefail is not recognized.The script worked just fine when I added "#!/bin/bash" to the top of the script. I suggest that you add it to the published script. I didn't even know my Virtual Box was defaulting to zsh until I started troubleshooting the script failure.

**Comment by mietek** [comment]
The setup script was meant to be POSIX-compatible, and this has slipped in unnoticed.  This is due to be corrected shortly, together with other setup-related improvements.

**Comment by mietek** [comment]
This is already tracked as https://github.com/mietek/halcyon/issues/63, and will also be resolved soon.
