### ISSUE TITLE
Automatically apply constraint differences

### ISSUE THREAD

**Issue by pbrisbin** [mietek/halcyon#69]
In common cases, where I expect to have to modify constraints (think: adding a single, new dependency), the steps seem very automate-able:
- Try to build, get failure
- Copy differences and apply with `patch`
- Build again

(I assume this is the expected approach in these cases, apologies if I'm missing something)

What about a flag, maybe `--update-constraints`, that automatically applies the output to `.halcyon/constraints` with `patch` and continues?

**Comment by mietek** [comment]
Sounds reasonable.

**Comment by mietek** [comment]
I’m sorry. This project is no longer maintained.
