### ISSUE TITLE
Support the various BSDs

### ISSUE THREAD

**Issue by pharpend** [mietek/halcyon#70]
The title is pretty explanatory.

**Comment by mietek** [comment]
Please be more specific. There already is an issue tracking FreeBSD support (https://github.com/mietek/halcyon/issues/37).  OS X is technically a BSD, and it’s already supported.

What have you tried? What did you wish worked, and didn’t?

**Comment by pharpend** [comment]
@mietek I looked through the setup script for "BSD", and didn't find anything. I was writing instructions elsewhere on installing a Haskell thing, and Halcyon only works on Mac/Linux, so I still had to write install instructions for Windows, OpenBSD, and FreeBSD.

Huh, I searched through the issues for 'BSD', and #37 didn't come up.

Closing as a duplicate of #37 .
