### ISSUE TITLE
Could you add a man page?

### ISSUE THREAD

**Issue by pharpend** [mietek/halcyon#71]
There are a small --- but stubborn --- selection of UNIX users, amongst which I am, who actually look at man pages as a method of figuring out how to use a program. Halcyon doesn't have a man page. Moreover, `halcyon --help` apparently doesn't support the use of a pager. That is, `halcyon --help | less` just has the last little bit of the help section; I can't scroll up.

If I'm using an X11 terminal, I can just scroll up. However, if I'm on a TTY console, this is a real issue.

Thanks,

Peter Harpending

**Comment by mietek** [comment]
> Moreover, `halcyon --help` apparently doesn't support the use of a pager.

Try `halcyon --help 2>&1 | less`.

**Comment by mietek** [comment]
With https://github.com/mietek/halcyon/commit/b8e36349c57640dae881f37bf43f968a400c57e7, it’s now possible to `halcyon --help | less`.

**Comment by mietek** [comment]
Adding a _man_ page would require installing it to one of the usual locations, or setting `MANPATH`.  Neither option is something I’d like to pursue at this stage.
