### ISSUE TITLE
Old versions of GHC (7.0 and 7.2) 'couldn't find timestamp record for given compiler/platform pair'

### ISSUE THREAD

**Issue by dbp** [mietek/halcyon#73]
I'm doing a little application archeology, and need to install some packages that don't work with modern versions of `base`. I tried to install an application using `7.0.4` and `7.2.2` (the two oldest versions supported by halcyon) and both errored out in the following way:

```
-----> Restoring GHC directory
       Extracting halcyon-ghc-7.0.4.tar.gz... done, 598MB

-----> Using existing Cabal directory

-----> Determining constraints
       cabal: Сouldn't find a timestamp record for the given compiler/platform pair.
       Please report this on the Cabal bug tracker:
       https://github.com/haskell/cabal/issues/new .
   *** ERROR: Failed to determine constraints
```

This is with an ubuntu 14.10 system.

**Comment by dbp** [comment]
Hmm. As a follow up, I don't think this is a problem with old versions, but with switching versions. Now running it with `halcyon install --ghc-version=7.8.4` produces the same error.

**Comment by mietek** [comment]
This is unexpected. Which Cabal version are you using?

**Comment by mietek** [comment]
I can’t reproduce this.  My simple test application, [_hello_](https://github.com/mietek/hello), installs successfully with all of the following:

* [GHC 7.0.4 and Cabal 1.20.0.3](https://gist.github.com/mietek/f72da417655b55d275bb#file-ghc-704-cabal-12003-txt)
* [GHC 7.0.4 and Cabal 1.22.2.0](https://gist.github.com/mietek/f72da417655b55d275bb#file-ghc-704-cabal-12220-txt)
* [GHC 7.2.2 and Cabal 1.20.0.3](https://gist.github.com/mietek/f72da417655b55d275bb#file-ghc-722-cabal-12003-txt)
* [GHC 7.2.2 and Cabal 1.22.2.0](https://gist.github.com/mietek/f72da417655b55d275bb#file-ghc-722-cabal-12220-txt)

**Comment by dbp** [comment]
@mietek In that case, let's close this. I don't actually think it was anything specific to 7.2, but rather switching between versions. I'll create a new issue if I can give an actual reproduction.

**Comment by mietek** [comment]
I wouldn’t expect switching _GHC_ versions to cause any issues.  On the other hand, switching _Cabal_ versions has already caused reproducible issues (https://github.com/haskell/cabal/issues/2320).

**Comment by mietek** [comment]
@dbp: Please also take a look at https://github.com/haskell/cabal/issues/2491.

**Comment by dbp** [comment]
Oh that seems possible. I was definitely switching while building. Is it
possible that a sandbox was left around? Or is the sandbox in /app ever
persisted?

**Comment by mietek** [comment]
Halcyon keeps track of the versions of GHC and Cabal used to build the Halcyon-managed sandbox, and should automatically prevent a version mismatch.  Perhaps you’ve had some leftover files in your project’s directory?

**Comment by dbp** [comment]
Certainly likely. I believe I tried to build without halcyon first before I
realized I needed an older version of GHC.
