### ISSUE TITLE
Bucket made in ireland (non us) can't be used

### ISSUE THREAD

**Issue by KasperJanssens** [mietek/halcyon#74]
I export the HALCYON_S3_ENDPOINT to endpoint for eu west 1, but every time Halcyon tries to upload I get a '000 unknown' error, like so (with 'boterhammekes' my Ireland bucket).

Uploading s3://boterhammekes/linux-ubuntu-14.04-x86_64/halcyon-ghc-7.8.4.tar.gz... 000 (unknown)

If I remove the endpoint export and point the bucket to a US bucket it seems to work. A bit annoying, especially the 'unknown' error. As you can see, linux, ubuntu 14.04, ghc 7.8.4, fresh clone of halcyon.

**Comment by mietek** [comment]
Can you quote the precise value you used for `HALCYON_S3_ENDPOINT`?

**Comment by mithrandi** [comment]
Note that the correct endpoint for Ireland is `s3-eu-west-1.amazonaws.com` (see the [list on the AWS website](http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region)).

**Comment by mietek** [comment]
Since this appears to be a recurring issue, I’ve now added a list of S3 endpoints to the [Halcyon reference](https://halcyon.sh/reference/#halcyon_s3_endpoint).

**Comment by mietek** [comment]
Resolved on IRC.
