### ISSUE TITLE
Add 'haddock' command

### ISSUE THREAD

**Issue by mounty1** [mietek/halcyon#75]
Currently, a couple of rather non-obvious (to mere users) commands are required to get documentation, so a single command to hide the Halcyon magic would be useful.  Until then, Mietek provides these workaround commands:

cabal --sandbox-config-file=/app/sandbox/cabal.sandbox.config configure
cabal --sandbox-config-file=/app/sandbox/cabal.sandbox.config build
cabal --sandbox-config-file=/app/sandbox/cabal.sandbox.config haddock [--executables]

adjusted to taste if you've set things up differently.

**Comment by mietek** [comment]
I’m sorry. This project is no longer maintained.
