### ISSUE TITLE
Shouldn't set up LD_LIBRARY_PATH to non-existent paths

### ISSUE THREAD

**Issue by pyrtsa** [mietek/halcyon#76]
[`src/paths.sh` sets up several paths](https://github.com/mietek/halcyon/blob/7210a8a338a20669dec5f2ef8b0708fb307e8d7a/src/paths.sh#L49-L53) that, however, aren't created. On OS X (10.10.3 with Xcode 6.3, to be accurate), that generates a linker warning when compiling Haskell as well as other projects. (I get a warning for every iOS project I build.)

I've got nothing against Halcyon taking precedence in my `*PATH` shell variables, but at least those folders should be created when setting up Halcyon.

Workaround and suggested fix: `mkdir -p <missing-paths>` seems to be enough (and fixed it for me).

**Comment by mietek** [comment]
Thanks, this is a fair point. Unfortunately, a proper solution isn’t that simple. I’m aware of the problem, and I’m tracking it as part of https://github.com/mietek/halcyon/issues/16.

**Comment by mietek** [comment]
To prevent Halcyon’s paths from affecting your iOS builds, you can remove the `eval "$( /app/halcyon/halcyon paths )"` line from your `~/.bash_profile`, and only activate the Halcyon environment manually when needed.

**Comment by pyrtsa** [comment]
I did that before but this problem still appeared (warnings in build log) when building Haskell projects with Halcyon.

I think a better fix was to create the said directories under `/app`, which is what I did and it helped.
