### ISSUE TITLE
Impossible to use exact GHC version with .halcyon files

### ISSUE THREAD

**Issue by dredozubov** [mietek/halcyon#77]
I notice that there are option to hardcode a cabal version with `.halcyon/cabal-version` in your repo, but no option to pinpoint the GHC version. Is there a reason for this?

**Comment by mietek** [comment]
Yes.  Currently, the GHC version is uniquely determined by the version of the `base` package, which is expected to be declared in the constraints file.  In the future, as we stop using `cabal freeze`, declaring the GHC version in a magic file will be allowed (https://github.com/mietek/halcyon/issues/52#issuecomment-79626776).
