### ISSUE TITLE
Archiving cabal directory, file name too long

### ISSUE THREAD

**Issue by jdwolk** [mietek/halcyon#79]
Hi there,

I'm attempting a `halcyon install` on OS X Yosemite 10.10.1 and receiving the following error:

```
Archiving Cabal directory
       Creating halcyon-cabal-1.20.0.3.hackage-2015-05-03.tar.gz... error
       /app/halcyon/lib/bashmenot/src/tar.sh: line 24: /var/tmp/halcyon-cache/halcyon-cabal-1.20.0.3.hackage-2015-05-03.tar.gz: File name too long
   *** ERROR: Failed to create cached archive
```

I also reset the `HALCYON_DEFAULT_CACHE` var in `src/main.sh` to `/var/tmp/hc` but that was still considered too long

**Comment by mietek** [comment]
This is very unusual. What are the precise values of any Halcyon options you are using? Can you quote the complete command line?

**Comment by jdwolk** [comment]
Sure! Just ran `halcyon install`. It failed fairly quickly compared to last time, leading me to think the cached files are still around. Here is full output:

```sh
➜  heyleo git:(json-serialization) ✗ halcyon install
-----> Self-updating bashmenot... done, 08977d6
-----> Self-updating Halcyon... done, 7210a8a
-----> Examining cache contents
       halcyon-cabal-1.20.0.3.tar.gz
       halcyon-ghc-7.8.4.tar.gz

cat: \033[1;35;40m\033[K.\033[m\033[K\033[1;35;40m\033[K/\033[m\033[K\033[1;35;40m\033[Kh\033[m\033[K\033[1;35;40m\033[Ke\033[m\033[K\033[1;35;40m\033[Ky\033[m\033[K\033[1;35;40m\033[Kl\033[m\033[K\033[1;35;40m\033[Ke\033[m\033[K\033[1;35;40m\033[Ko\033[m\033[K\033[1;35;40m\033[K.\033[m\033[K\033[1;35;40m\033[Kc\033[m\033[K\033[1;35;40m\033[Ka\033[m\033[K\033[1;35;40m\033[Kb\033[m\033[K\033[1;35;40m\033[Ka\033[m\033[K\033[1;35;40m\033[Kl\033[m\033[K: No such file or directory
-----> Installing GHC and Cabal
       External storage:                         public
       GHC version:                              7.8.4
       Cabal version:                            1.20.0.3
       Cabal remote-repo:                        hackage:http://hackage.haskell.org/packages/archive

-----> Using existing GHC directory

-----> Locating Cabal directories
       Listing https://halcyon.global.ssl.fastly.net/?prefix=osx-10.10-x86_64/halcyon-cabal-1.20.0.3-hackage... done
-----> Restoring Cabal directory
       Extracting halcyon-cabal-1.20.0.3.tar.gz... done, 15MB
-----> Updating Cabal directory
       Updating Cabal package database... done, 201MB
-----> Archiving Cabal directory
       Creating halcyon-cabal-1.20.0.3.hackage-2015-05-05.tar.gz... error
       /app/halcyon/lib/bashmenot/src/tar.sh: line 24: /var/tmp/halcyon-cache/halcyon-cabal-1.20.0.3.hackage-2015-05-05.tar.gz: File name too long
   *** ERROR: Failed to create cached archive
```

**Comment by mietek** [comment]
I’ve just ran a test on my OS X 10.10.2 system, and everything is working as expected.

There are a few unexpected lines in your output.

#### Unexpected `cat`
```
cat: \033[1;35;40m\033[K.\033[m\033[K\033[1;35;40m\033[K/\033[m\033[K\033[1;35;40m\033[Kh\033[m\033[K\033[1;35;40m\033[Ke\033[m\033[K\033[1;35;40m\033[Ky\033[m\033[K\033[1;35;40m\033[Kl\033[m\033[K\033[1;35;40m\033[Ke\033[m\033[K\033[1;35;40m\033[Ko\033[m\033[K\033[1;35;40m\033[K.\033[m\033[K\033[1;35;40m\033[Kc\033[m\033[K\033[1;35;40m\033[Ka\033[m\033[K\033[1;35;40m\033[Kb\033[m\033[K\033[1;35;40m\033[Ka\033[m\033[K\033[1;35;40m\033[Kl\033[m\033[K: No such file or directory
```
Without the ANSI control codes, this reads:
```
cat: ./heyleo.cabal: No such file or directory
```
I don’t know what’s causing this to appear, or why is it peppered with ANSI control codes.

Does this happen every time you run `halcyon install`?

#### Unexpected archive name
```
       Creating halcyon-cabal-1.20.0.3.hackage-2015-05-05.tar.gz... error
```
On my OS X system, and in fact, on all the systems I’ve tested, this reads:
```
       Creating halcyon-cabal-1.20.0.3-hackage-2015-05-05.tar.gz... error
```
Note a dash (`-`) is expected instead of a dot (`.`) between the Cabal version and the remote repo name.  The only reason I can see for this difference is that your _bash_ shell somehow has a different interpretation of the following:
```bash
echo "halcyon-cabal-${cabal_id}${repo_name:+-${repo_name}${cabal_date:+-${cabal_date}}}.tar.gz"
```
What shell are you using?

**Comment by jdwolk** [comment]
I'm using zsh inside of tmux -- I think tmux explains the control codes since I don't have that `cat` line when I run outside of tmux with bash, but I still get this error:

```
bash-4.3$ halcyon install
-----> Self-updating bashmenot... done, 08977d6
-----> Self-updating Halcyon... done, b1edd5e
-----> Examining cache contents
       halcyon-cabal-1.20.0.3.tar.gz
       halcyon-ghc-7.8.4.tar.gz

-----> Installing GHC and Cabal
       External storage:                         public
       GHC version:                              7.8.4
       Cabal version:                            1.20.0.3
       Cabal remote-repo:                        hackage:http://hackage.haskell.org/packages/archive

-----> Using existing GHC directory

-----> Locating Cabal directories
       Listing https://halcyon.global.ssl.fastly.net/?prefix=osx-10.10-x86_64/halcyon-cabal-1.20.0.3-hackage... done
-----> Restoring Cabal directory
       Extracting halcyon-cabal-1.20.0.3.tar.gz... done, 15MB
-----> Updating Cabal directory
       Updating Cabal package database... done, 201MB
-----> Archiving Cabal directory
       Creating halcyon-cabal-1.20.0.3.hackage-2015-05-06.tar.gz... error
       /app/halcyon/lib/bashmenot/src/tar.sh: line 24: /var/tmp/halcyon-cache/halcyon-cabal-1.20.0.3.hackage-2015-05-06.tar.gz: File name too long
   *** ERROR: Failed to create cached archive
```

**Comment by mietek** [comment]
Can you quote the precise version of GNU _bash_ you have installed?  How did you install it?

**Comment by jdwolk** [comment]
```sh
bash-4.3$ bash --version
GNU bash, version 4.3.33(1)-release (x86_64-apple-darwin14.1.0)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
```
I don't recall installing it, think it's just my builtin. I'm on OS X Yosemite 10.10.1 (14B25)

**Comment by mietek** [comment]
I have the exact same version, installed using `brew`.  What does `which bash` say?

**Comment by jdwolk** [comment]
```sh
bash-4.3$ which bash
/usr/local/bin/bash
```

**Comment by mietek** [comment]
Looks like `brew`, too. Can you create a brand-new OS X user account, and try running `halcyon install` there?

**Comment by jdwolk** [comment]
OK, so after creating a new OS X user account and running the halcyon install scripts as the new user, `halcyon install` works.

When I switch back to my normal account, I didn't have permission into anything in `/app`, so I `sudo chown -R` everything in `/app` from my normal account.

Thereafter, running, i.e. `halcyon constraints` in my Haskell project directory still gives me the `File name too long error`

**Comment by mietek** [comment]
I hope this makes it clear the problem exists somewhere in the configuration of your usual user account.  You’re the only person who can diagnose it.  I’d start with taking a close look at the contents of your `~/.bashrc`, `~/.bash_profile`, and `~/.profile` files.

**Comment by jdwolk** [comment]
Fair enough, thank you for your suggestions

**Comment by mietek** [comment]
You’re welcome. I’m very much interested in the outcome, as this is the strangest Halcyon-related issue I’ve seen so far.
