### ISSUE TITLE
Support building GHC from source

### ISSUE THREAD

**Issue by mietek** [mietek/halcyon#8]
Moved from https://github.com/mietek/haskell-on-heroku/issues/15.

**Comment by reneklacan** [comment]
Is there currently a way to install ghcjs?

**Comment by mietek** [comment]
@reneklacan: Installing GHCJS doesn’t seem to require building GHC from source any more, so this issue isn’t relevant.

**Comment by reneklacan** [comment]
Ok, thanks!
