### ISSUE TITLE
Installing extra data files no longer works

### ISSUE THREAD

**Issue by begriffs** [mietek/halcyon#80]
My project has a `.halcyon` folder including extra-data-files. Installation worked fine a few days ago but now I get the error

```
    amazon-ebs: -----> Restoring install directory
    amazon-ebs: Downloading s3://etcetc/linux-amzn-2014.09-x86_64/ghc-7.8.4/halcyon-install-b7a5178-goodtimes-0.1.0.0.tar.gz... 404 (not found)
    amazon-ebs: -----> Preparing install directory
    amazon-ebs: Installing extra data files
    amazon-ebs:    *** ERROR: copy_dir_entry_into: Expected existing /tmp/halcyon.P5rShN9Bxq/build-goodtimes-0.1.0.0.R4E1nYi3xI/public
    amazon-ebs:    *** ERROR: Failed to install extra data files
```

I think the folder `/tmp/halcyon.P5rShN9Bxq` doesn't exist. This is on amazon linux. I get the error whether I use cached assets from S3 or build everything from scratch.

I'm trying to see if anything about my project has changed, but it right now it doesn't seem like it. Maybe Halcyon got updated?

**Comment by mietek** [comment]
There were no changes since 29 March. Please list the contents of your project directory, and the `.halcyon/extra-data-files` file.

**Comment by begriffs** [comment]
False alarm, it turns out a file had gone missing that was expected by `extra-data-files`.

**Comment by mietek** [comment]
Glad to hear the issue is resolved.
