### ISSUE TITLE
Installing another package after installed ghci-ng breaks ghci-ng

### ISSUE THREAD

**Issue by spwhitton** [mietek/halcyon#84]
# Steps to reproduce

1) Fresh Debian Jessie 32-bit
2) Install halcyon with setup.sh
3) `halcyon install https://github.com/chrisdone/ghci-ng`
4) Try installing something else e.g. `halcyon install alex`
# What's expected

ghci-ng still works.
# What happens

ghci-ng fails to start with the error:

```
ghci-ng: error while loading shared libraries: libHSsyb-0.4.4-ghc7.8.4.so: cannot open shared object file: No such file or directory
```
# Workaround

Running `halcyon install https://github.com/chrisdone/ghci-ng` again makes ghci-ng work again.  Obviously it's undesirable to have to run this after every install with halcyon.
# Commentary

This is the steps-to-reproduce for a bug I discussed with Mietek by e-mail on the 22nd of February of this year.  I hope it's useful to you and thanks for your work on halcyon.

**Comment by mietek** [comment]
Thanks for the report. It seems that the issue is that _ghci-ng_ wants to dynamically link with its dependencies, even if they’re installed in a sandbox:
```
$ halcyon install http://github.com/chrisdone/ghci-ng
$ rm -rf /app/sandbox
$ ghci-ng
ghci-ng: error while loading shared libraries: libHSghc-paths-0.1.0.9-ghc7.8.4.so: cannot open shared object file: No such file or directory
```
Since Halcyon keeps a single sandbox, building another project will almost always remove these dependencies and break _ghci-ng._  The offending files are:
```
/app/sandbox/lib/x86_64-linux-ghc-7.8.4/ghc-paths-0.1.0.9/libHSghc-paths-0.1.0.9-ghc7.8.4.so
/app/sandbox/lib/x86_64-linux-ghc-7.8.4/syb-0.4.4/libHSsyb-0.4.4-ghc7.8.4.so
```

One solution might be to link _ghci-ng_ statically, by passing the GHC option `-static`, via the Cabal option `--ghc-options`, via the Halcyon option [`--extra-configure-flags`](https://halcyon.sh/reference/#halcyon_extra_configure_flags):
```
$ halcyon install http://github.com/chrisdone/ghci-ng --extra-configure-flags='--ghc-options=-static'
$ rm -rf /app/sandbox
$ ghci-ng
GHCi-ng, version 7.8.4 [NG/0.0.0]: http://www.haskell.org/ghc/  :? for help
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... linking ... done.
Loading package base ... linking ... done.
Prelude> 
```

CC @chrisdone

**Comment by mietek** [comment]
@spwhitton ping

**Comment by spwhitton** [comment]
@mietek pong

What's up?  Would you like me to test it on my machine using --static?

**Comment by mietek** [comment]
Yes, please.  There’s not much I can do about how _ghci-ng_ works.  Also, the single-sandbox assumption will remain in Halcyon until I implement support for package-level granularity — that is, for a while.

**Comment by spwhitton** [comment]
Your solution where one runs

    $ halcyon install http://github.com/chrisdone/ghci-ng \
    --extra-configure-flags='--ghc-options=-static'

works on my machine.  HTH!

Perhaps this ought to be added to the Halcyon guide as a potential pitfall when working with some packages, with a workaround.

**Comment by mietek** [comment]
I’m sorry. This project is no longer maintained.
