### ISSUE TITLE
Add sources with git url + directory

### ISSUE THREAD

**Issue by etorreborre** [mietek/halcyon#85]
I was hoping to be able to use halcyon without having to use git submodules but I don't think I can. If I try to add a specific git branch to `sandbox-sources` there is an implicit assumption (unless I'm wrong) that the git url is a directory containing a cabal file. However we sometimes depend on projects like [this one](https://github.com/ambiata/disorder.hs) which contains several sub-projects.

 - is it possible to extend the `halcyon install` to specify a relative path in addition to a git url?
 - is there a workaround (other than using git submodules and depend on local paths)?

**Comment by mietek** [comment]
Thanks for the report. You’re right, and this is already tracked as part of https://github.com/mietek/halcyon/issues/11.

One workaround could be to use a sandbox pre-build hook, in which you clone the repository to a subdirectory of `/app/sandbox` (by default), and call `cabal add-source` yourself.  I’m sorry, but I don’t have a good example for this yet.  The closest I do have is a sandbox pre-build hook used for another purpose, in [_halcyon-recursive-example_](https://github.com/mietek/halcyon-recursive-example).
