### ISSUE TITLE
Space level estimation to prevent "no space left" crashes.

### ISSUE THREAD

**Issue by dredozubov** [mietek/halcyon#87]
Currently it's not exactly pleasant to use halcyon on small(and possibly elastic) nodes, because it can do its thing for awhile and will crash with "no space left" kind of error. It can be quite frustrating, because you wait for some time and get something like this:
 `/app/halcyon/src/tag.sh: line 85: cannot create temp file for here-document: No space left on device`

I guess it would be quite useful to have some kind of warning with some space estimation in the lines of: "your project would probably use xxx Mb/Gb of disk space and you may want to free some space, because you have yyy Mb/Gb of space left".

@mietek Do you have a clue how it can be estimated? Would you consider this kind of warning useful?

**Comment by mietek** [comment]
I’m sorry. This project is no longer maintained.
