### ISSUE TITLE
Support for EC2 Instance Profile Credentials

### ISSUE THREAD

**Issue by srijs** [mietek/halcyon#92]
I'm looking into using Halcyon in a setup on AWS where the permissions are managed via EC2 instance credentials. So I would like the private storage module to pick the credentials up via the instance profile endpoint, instead of the usual "HALCYON_AWS_ACCESS_KEY_ID" and "HALCYON_AWS_SECRET_ACCESS_KEY" variables.

Would that be possible? I'm willing to have a look into adding the feature myself, if anybody could point me into the right direction.

**Comment by mietek** [comment]
I’m sorry. This project is no longer maintained.
