### ISSUE TITLE
When to support OS X 10.11 ?

### ISSUE THREAD

**Issue by bluealert** [mietek/halcyon#93]
When to support OS X 10.11 ?  Thank you very much! :)

**Comment by davidpdrsn** [comment]
I'm also having issues on 10.11

```
$ eval "$( curl -sL https://github.com/mietek/halcyon/raw/master/setup.sh )"
-----> Welcome to Halcyon
install_halcyon:17: read-only variable: status
```

**Comment by mietek** [comment]
Sorry, OS X 10.11 is not supported yet.

**Comment by peter** [comment]
Any plans to supporting the Mac, i.e. OS X (10.11)? What needs to be done to make that happen? Any pointers on doing a Heroku deployment without Halcyon?

**Comment by mietek** [comment]
I’m sorry. This project is no longer maintained.
